# View pre-commit hooks at https://github.com/pre-commit/pre-commit-hooks#hooks-available
# !!!RUN pre-commit autoupdate!!! To get the latest versions. This gist has been collecting cob webs.
# The commented repos/hooks will NOT autoupdate! If you're going to use them, uncomment and run pre-commit autoupdate.

default_language_version:
    python: python3.8

default_stages: [commit, push]

fail_fast: true

minimum_pre_commit_version: '1.15.0'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: forbid-new-submodules
    -   id: name-tests-test
    -   id: pretty-format-json
        args:
          - --autofix
          - --indent=4
          - --no-ensure-ascii
          - --no-sort-keys
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]  # Preserve Markdown hard linebreaks
-   repo: https://github.com/psf/black
    rev: 88d12f88a97e5e4c8fd0d245df0a311e932fd1e1
    hooks:
    -   id: black
        args:
          - --target-version=py38
          - --line-length=79
          - --verbose
-   repo: https://github.com/timothycrosley/isort
    rev: 6df7ef4f2044a7d0eadff657e6e29ba0e6fee081
    hooks:
    -   id: isort
        args:
          - --trailing-comma
          - --use-parentheses
          - --balanced
-   repo: https://gitlab.com/pycqa/flake8
    rev: b6d3fcacff501a7d0a59dabc506614721e0b2918
    hooks:
    -   id: flake8
        args:
          - --doctests
-   repo: https://github.com/asottile/add-trailing-comma
    rev: 4737c82eefc7cbe6028bb5e2fc6619a38cd0de76
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/myint/docformatter
    rev: 1cceff608f597fd9c07a266ea655d54a9cf494aa
    hooks:
      - id: docformatter
        args: [--in-place]
# Below is opinionated lintesr and formatters. Uncomment at your own risk!
# -   repo: https://github.com/econchick/interrogate
#     rev: 7a0823fb29ddcd955eaf3aa91e7e93c8ca6bfbfd
#     hooks:
#     -   id: interrogate
#         args: [--quiet, --fail-under=95, --verbose, --ignore-init-method, --ignore-init-module]
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: f687d36b12cd72d417bba07599ff27e734161768
#     hooks:
#     -   id: mypy
#         args: [--no-strict-optional, --ignore-missing-imports]
# -   repo: https://github.com/asottile/reorder_python_imports
#     rev: 925baf70b8fe1467ac1712ddd6793d52978a4a72
#     hooks:
#     -   id: reorder-python-imports
# -   repo: https://github.com/PyCQA/bandit
#     rev: b78c938c0bd03d201932570f5e054261e10c5750
#     hooks:
#     -   id: bandit
# -   repo: https://github.com/APIDevTools/swagger-cli
#     rev: 9fec0bce6954a1bf7d396a6356f9c93780a92da7
#     hooks:
#     -   id: swagger-validation
#         args: ["validate", "<path to root swagger>"]
# - repo:  https://github.com/milin/giticket  # View docs to see how to set up custom ticket.
#   rev: <grab the latest commit hash>
#   hooks:
#   - id:  giticket
#     args: ['--regex=PROJ-[0-9]', '--format={ticket} {commit_msg}']  # Optional

