site_name: Evan Baird
site_author: Evan Baird
site_description: Yet another Python blog
copyright: "Copyright &copy; 2020 Evan Baird"
site_url: https://evanbaird.io
repo_url: https://github.com/mrcartoonster/website
repo_name: mrcartoonster/website
theme:
  name: material
  palette:
    primary: deep orange
    secondary: orange
  icon:
    repo: fontawesome/brands/github
  favicon: images/favicon.ico
  logo: images/8596846.jpg
nav:
 - Home: index.md
markdown_extensions:
 - markdown.extensions.codehilite:
     guess_lang: false
 - extra
 - admonition
 - codehilite
extra:
  discus: evan-2
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/mrcartoonster/website
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/mrcartoonster
  - icon: fontawesome/brands/dev
    link: https://dev.to/mrcartoonster
  - icon: fontawesome/brands/gitter
    link: https://gitter.im/Worldsworstpythonista/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
